Book endpoint integration test
hamzachikar/book-store pull request #18
Opened 2021-02-22 18:15 UTC by hamzachikar

hello guys can you please see my updates in the BookControllerIntegrationTest #2

2021-02-22 18:39 UTC, mothmane requested changes

2021-02-22 18:39 UTC, mothmane commented on src/test/java/com/app/store/BookControllerIntegrationTest.java
> +@ExtendWith(SpringExtension.class)
the ExtendWith is now part of the annotation SpringBootTest you can delete it from here

2021-02-22 18:39 UTC, mothmane commented on src/test/java/com/app/store/BookControllerIntegrationTest.java
> +                 testRestTemplate.postForEntity("http://localhost:"+port+"/books",book,Book.class);
build the uri outside this call in a local variable

2021-02-22 18:39 UTC, mothmane commented on src/test/java/com/app/store/BookControllerIntegrationTest.java
> +    @Test
separe the given when then for readability

2021-02-22 18:39 UTC, mothmane commented on src/test/java/com/app/store/BookControllerIntegrationTest.java
> +        final ResponseEntity<Book> bookResponseEntity=
No need for final keywork

2021-02-22 18:39 UTC, mothmane commented on src/test/java/com/app/store/BookControllerIntegrationTest.java
> +        final ResponseEntity<Book> bookResponseEntity=
No need for type also

2021-02-22 18:39 UTC, mothmane commented on src/test/java/com/app/store/BookControllerIntegrationTest.java
> +        );
you should check that the get do not return this book 
checking that no exception is throw is not necesseary that the integration test is working

2021-02-22 18:39 UTC, mothmane commented on src/test/java/com/app/store/BookControllerIntegrationTest.java
> +        System.out.println(bookResponseEntity.getBody());
remove this line

2021-02-23 11:00 UTC, ichrak2 approved these changes

2021-02-23 17:35 UTC, mothmane approved these changes

2021-02-23 17:44 UTC, merged